use_frameworks!

platform :ios, '9.0'

target 'FSOCUtils_Example' do
  pod 'FSOCUtils', :path => '../'
  pod 'FSOCUtils/EncyptUtils', :path => '../'

  target 'FSOCUtils_Tests' do
    inherit! :search_paths

    
  end
end
